### ISSUE TITLE
Unable to get the examples working using the Quick Guide

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-hyperty-toolkit#1]
So before writing my own hyperty, I wanted to make sure the examples work, so I followed the quick guide.

1. I executed `npm install` and `npm start`
2. I added `127.0.0.1		hybroker.rethink.ptinovacao.pt` to my hosts file
3. I access the website using `https://hybroker.rethink.ptinovacao.pt/examples/`

No matter what example I select, this is how the log looks: [hybroker.rethink.ptinovacao.pt-1461771593131.txt](https://github.com/reTHINK-project/dev-hyperty-toolkit/files/238921/hybroker.rethink.ptinovacao.pt-1461771593131.txt)

There is always this error `WebSocket connection to 'wss://msg-node.localhost:9090/ws' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

What am I doing wrong? Do I need to have a msg node running? It doesn't say so in the Quick guide. I tried it by accessing `https://localhost/examples/`, but it's the same. I tried starting it with `npm start --production` but that didn't help either.

**Comment by sbecot** [comment]
Maybe your proxy refuses wss? I did install the example here https://tuto.rethink.orange-labs.fr/examples/ but I have an empty list of Hyperty. Probably something is wrong.
By the way, this example still need to be enhanced. Here are some proposals
* it is said to be read-only, but the instruction is to create a folder in src directory.
* don't put 4 examples, one is enough.
* describe quickly the function of the example -and reporter hyperty + observer hyperty is not useful at this stage (and by the way the pattern is not described before -please don't describe it-).
* add a picture to figure out what is deployed where: we can't figure out why to use pt platform to deploy an example on a local machine. And I don't understand the localhost config (127.0.0.1   hybroker.rethink.ptinovacao.pt). If we need to install a messaging node first, let's do it, I think it may be more clear. It could be easily done thought a docker container.
* The examples should be provided directly in ES5 to avoid a step.
* Before step 2 the command npm start should be run, but it is not specified.
* _set the cloud development environment domain at system.config.json_ is not very clear, the example specify production and development, but not cloud.

Probably to be discussed next week. We need an Hello World time slot.

**Comment by pchainho** [comment]
@Endebert @sbecot are you still having these issues ? 

Anyway, I suggest you join https://rethink-project.slack.com/messages/dev-hyperty/ to have a faster.

@sbecot regarding the Hello World and documentation feedback in general, I propose to discuss in other issue

**Comment by Endebert** [comment]
Still none of them work. This is when selecting the chat hyperty in development mode: [localhost-1461921471178.txt](https://github.com/reTHINK-project/dev-hyperty-toolkit/files/242031/localhost-1461921471178.txt)

**Comment by shumy** [comment]
It seems that you want to use the local server with the "hybroker" msg-node. It's possible if you follow the steps:
1. Using the stable version at "dev-hyperty-toolkit" "master" branch.
2. Change the files:
  * system.config.json -> on development config set "domain": "hybroker.rethink.ptinovacao.pt"
  * resources/descriptors/ProtoStubs.json -> on default config set "url": "wss://msg-node.hybroker.rethink.ptinovacao.pt/ws"
  * your system hosts file -> add "127.0.0.1 hybroker.rethink.ptinovacao.pt catalogue.hybroker.rethink.ptinovacao.pt"
3. Start server with "npm run start:dev"

**Comment by Endebert** [comment]
Ok that seems to have fixed it, but none of this is mentioned in the quick guide, especially setting catalogue.hybroker.rethink.ptinovacao.pt in the hosts file.

**Comment by pchainho** [comment]
yes, that was missing in the quick guide, sorry

**Comment by shumy** [comment]
Yes, but you are using a very specific config. Using you local server with the remote (hybroker) msg-node.

**Comment by Endebert** [comment]
I'm just following the quick guide. The quick guide says:

1. clone repository
2. run `npm install` and `npm start` or `npm run start:dev`, without explaining what either of those do or what I need to have it properly running
3. can I skip because I'm not using my own hyperty yet

Then it goes back to 1.
1a. expose ... don't need that yet
1b. don't need that either
1c. change your hosts, which i did
2. open https://localhost/examples/

And that's it. After that comes the section "Cloud and Local development environment", which I don't care about, because I just want to get it running with the default settings. And as it is mentioned there, the toolkit is *preconfigured*.

What should I have done instead?

**Comment by pchainho** [comment]
you have followed the right steps, @Endebert , but the configuration defined in the repo was not  aligned with the quick guide. This was fixed. If you use the most updated version in master it should be fine. Could you have a try?

**Comment by Endebert** [comment]
it works
