### ISSUE TITLE
Unable to create MessageFactory

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-hyperty-toolkit#10]
I don't know if this problem is specific to the toolkit, but importing and instantiating MessageFactory from the service-framework doesn't work and throws an error.

Code:

```
import MessageFactory from 'service-framework/dist/MessageFactory';
...
let messageDescURL = 'hyperty-catalogue://' + this._domain + '/.well-known/dataschemas/Message';
let messageFactory = new MessageFactory(false, messageDescURL);
```

Error:

```
main.js:11 Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': An object could not be cloned.
    window._miniBus._onPostMessage @ main.js:11
    e.value @ main.js:9
    u.value @ main.js:10
    (anonymous function) @ main.js:10
    (anonymous function) @ main.js:9
    u.value @ main.js:9
    e.value @ main.js:9
    (anonymous function) @ main.js:11
```

I added the Message schema manually to the toolkit, since it wasn't provided.

**Comment by pchainho** [comment]
Is this issue still pending? the develop branch has now the source map of the runtime core to make logs more meaningful...

**Comment by Endebert** [comment]
I still get the error:
```
main.js:250 Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': An object could not be cloned.
	window._miniBus._onPostMessage 	@ main.js:250
	value 							@ main.js:248
	value 							@ main.js:249
	(anonymous function) 			@ main.js:249
	(anonymous function) 			@ main.js:248
	value 							@ main.js:248
	value 							@ main.js:248
	(anonymous function) 			@ main.js:250
```

**Comment by pchainho** [comment]
still pending?

**Comment by Endebert** [comment]
Just had a look at it again.

The cause of the exception is that in the `import` line I needed to import `{MessageFactory}` instead of just `MessageFactory`, which resulted in `MessageFactory` being undefined, therefore `new MessageFactory()` throws an exception.

But because of the `DataCloneError`, the initial exception was not logged.
