### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by KCorre** [reTHINK-project/dev-hyperty-toolkit#13]
Hi all,

Sorry for not saying much on the toolkit debrief meeting. I have indeed some comments to make as I tried to use it. Here is my feedback

Overall, the toolkit is working. I am using MacOSX on an open network. Though I had some problem to start the toolkit with port 443. I had to do sudo npm run start:dev.

However I did not try to do a new hyperty. I was trying to make an application that would then use hyperties. For me it seemed more logical to have an application first and then think of how an hyperty could be used in this context.
I did not manage to reach my goal as I was trying to use the runtime in dist/main.js. I finally managed to do what I wanted when Nicolas Daviaud from Apizee showed me his application.

For me the toolkit is not giving enough information on that matter. The whole toolkit bundle too much things together and abstract too much individual steps that it becomes unclear what is happening. So a few remarks:
- The dist/main.js file is bundled with references to the demonstration application (the page with the dropbox) and if it's possible to use it outside of that page, it's not made clear.
- The whole toolkit is linked with the set structure of an hyperty+a script+an handlebar template. However, I may not want to use an hyperty in this structure, and I surely don't want to learn handlebars now. This is a clean setup for an official demo, but too cumbersome to learn how to do it in a few minutes.
- Modyfing the host, hide what is happening behind the scene. With npm run start:dev we host stuff on locahost, why not modify a config file so that locahost is used? I think that currently this even forbid to test crossdomain with hybroker@pt and localhost.
- The deployment is done in a single npm command. That's ultra clean, but then it does not show the actual details. If I want to developp an hyperty, I may want to understand what is happening, in more details that what is currently available.

A few suggestion
1) Give a simple demonstration application in the toolkit so that first, developpers can understand how it's going to be used. Hyperty are a mean, not a goal.
1b) This demonstration would then require the runtime. Either download online or in a directory of the toolkit.
2) Reduce the amount of work required to developp a new hyperty, no fancy template engine, no fixed set of scripts. Use the previous simple application in the tutorial so that the developper can test it directly.

Kevin

**Comment by KCorre** [comment]
I will see if I can do a bit much. At the moment I can't answer most questions in the google survey. 

Also note that I modified the demo application in the testbed, we will deploy it soon and push on github. Testbed is probably not the right place for it anyway.

**Comment by pchainho** [comment]
> Overall, the toolkit is working. I am using MacOSX on an open network. Though I had some problem to start the toolkit with port 443. I had to do sudo npm run start:dev.

pls see #5 

> The dist/main.js file is bundled with references to the demonstration application (the page with the dropbox) and if it's possible to use it outside of that page, it's not made clear.
The whole toolkit is linked with the set structure of an hyperty+a script+an handlebar template. However, I may not want to use an hyperty in this structure, and I surely don't want to learn handlebars now. This is a clean setup for an official demo, but too cumbersome to learn how to do it in a few minutes.

The idea was to speed-up the tests for the development of a new Hyperty, not the development of Apps. App development Guidelines and examples should be provided somewhere else.

> Modyfing the host, hide what is happening behind the scene. With npm run start:dev we host stuff on locahost, why not modify a config file so that locahost is used? I think that currently this even forbid to test crossdomain with hybroker@pt and localhost.

This is not clear. Nevertheless we have enabled crossdomain testing with toolkit in the development branch.

> The deployment is done in a single npm command. That's ultra clean, but then it does not show the actual details. If I want to developp an hyperty, I may want to understand what is happening, in more details that what is currently available.

We think we have already addressed this issue. But pls let us know if you think more details are still needed.

> 1) Give a simple demonstration application in the toolkit so that first, developpers can understand how it's going to be used. Hyperty are a mean, not a goal.
1b) This demonstration would then require the runtime. Either download online or in a directory of the toolkit.

Agree, but not sure if this should be in this repo or in another one.

> 2) Reduce the amount of work required to developp a new hyperty, no fancy template engine, no fixed set of scripts. Use the previous simple application in the tutorial so that the developper can test it directly.

Templates were just used to speed-up tests of developed Hyperties. But anyway we'll review the current approach.

**Comment by pchainho** [comment]
These suggestions should have been addressed mainly in branch toolkit-node and also in the dev-app repo.

See also the DTWebRTC Hyperty that is not using Templates.

Pls reopen if needed
