### ISSUE TITLE
Hyperties.json and DataSchemas.json should be empty initially

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-hyperty-toolkit#15]
Could you please make the object in [/resources/descriptors/Hyperties.json](https://github.com/reTHINK-project/dev-hyperty-toolkit/blob/master/resources/descriptors/Hyperties.json) and [/resources/descriptors/DataSchemas.json](https://github.com/reTHINK-project/dev-hyperty-toolkit/blob/master/resources/descriptors/DataSchemas.json) empty? Their content is being generated on start anyways, and now that I have updated my room hyperties, they have hyperties/schemas inside them that aren't being used anymore.

Also saves >3MB when downloading the toolkit

**Comment by pchainho** [comment]
Agree

**Comment by vitormsilva** [comment]
I'm working on this, on branch [develop-improves](https://github.com/reTHINK-project/dev-hyperty-toolkit/tree/develop-improves)..

but to work with the pre configurated hyperty, you need to add on [dev-hyperty/develop (ef)](https://github.com/reTHINK-project/dev-hyperty/tree/develop) repository the initial configuration file.

Look at this issue #12;
