### ISSUE TITLE
Fake storage manager on toolkit

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-hyperty-toolkit#23]
@Endebert, seems the david fix the issue [61](https://github.com/reTHINK-project/dev-runtime-browser/issues/61).. but while we don't have it on toolkit we make a "fake" StorageManager which only have promises..
The point is, have an implementation while we don't have the [dev-hyperty-toolkit](https://github.com/reTHINK-project/dev-hyperty-toolkit/tree/toolkit-storage-manager) ready to use the it, from runtime-browser or runtime-nodejs.

I think you on RuntimeCatalague need to catch the error thrown by the StorageManager, if works it this "fake" implementation should works too with version of runtime-nodejs or runtime-browser..

**Comment by Endebert** [comment]
I disagree. A database lacking an entry for a given key is not an error, as I explained in the other issue.

Fixing your fake StorageManager to not throw an exception in such a case seems like an easier solution than extending error handling in the RuntimeCatalogue.

I might extend error handling in RuntimeCatalogue for interactions with the StoageManager in the future. But currently, the RuntimeCatalogue does not work properly if the StorageManager does not work properly. This will stay this way until the StorageManager has matured a little.

**Comment by vitormsilva** [comment]
I did what you say and it's working, but i don't agree with the solution..
If an error is thrown, that error should be catched 

Closing this issue..
