### ISSUE TITLE
Info on how to link to folder containing external hyperties (not on dev-hyperty-toolkit)

### ISSUE THREAD

**Issue by aoncorici** [reTHINK-project/dev-hyperty-toolkit#3]
Extend the dev-hyperty-toolkit to load source folders of hyperties, e.g. from dev-hyperty

**Comment by aoncorici** [comment]
Provide short documentation (which files to change) in order to be able to load other hyperties than those from dev-hyperty-toolkit/src.

**Comment by vitormsilva** [comment]
I will make changes to the master branch in dev-hyperty and dev-hyperty-toolkit, with the following changes:

- only have the examples, docs, src and test folders;
- your last commits in the master branch will be maintained and up to date;
- the src folder and examples will be copied to the dev-hyperty-toolkit when you start the toolkit;
- in the examples folder, you have a main.js file with the switch case where you can define the hyperties and templates to be used;

In the dev-hyperty-toolkit the src and examples folder will be removed
Then you need to have the dev-hyperty in the same root as the dev-hyperty-toolkit. When you start the toolkit with sudo npm run start:dev will ask you to select where is the dev-hyperty repository. Then you just have to work with the source code in dev-hyperty repository. All changes in your hyperty source will be automatically handled by the hyperty-toolkit and provisioned in the local catalogue enabling you to immediately test what you are developing.

Any question, comment?

**Comment by vitormsilva** [comment]
This was done.
If you have issues, hints and tips related with this, please open a new issue.

closing issue;
