### ISSUE TITLE
Toolkit with develop branches

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-hyperty-toolkit#35]
Hi, @reTHINK-project/wp3

All of you should use the develop branch of toolkit;

This branch has:
- the runtime-core in develop branch
- the service-framework in develop branch
- the runtime-browser in dev-inteworking branch (i think, the develop branch need to be merged with the dev-inteworking branch) and after that we can use develop branch, right @dvilchez 

Now you have a single toolkit branch to run all runtime types including the `runtime-core`, `runtime-browser` and `runtime-nodejs` (to be supported very soon);
You could choose which one you want to start, doing the following command:
```shell
# runtime-core
npm run start:dev

# runtime-browser
npm run start:browser
```

**Comment by dvilchez** [comment]
@vitormsilva I just merged dev-interworking with develop branch, you can move to develop branch now.
