### ISSUE TITLE
Alternative Port

### ISSUE THREAD

**Issue by Trikolon** [reTHINK-project/dev-hyperty-toolkit#5]
Please add an alternative port to 443 that does not require sudo/root on linux systems.

**Comment by vitormsilva** [comment]
Someone found a solution, I think was @Endebert.

The solution is something like this:

```shell
setcap 'cap_net_bind_service=+ep' /path/to/program
```

**Comment by pchainho** [comment]
fixed

**Comment by Endebert** [comment]
@pchainho how do I change the port? I couldn't find it in the readme

**Comment by pchainho** [comment]
the readme is still not updated but the idea is to use the docker image.
