### ISSUE TITLE
npm install fails on Windows with "EPERM, operation not permitted" error during rename

### ISSUE THREAD

**Issue by acheambe** [reTHINK-project/dev-hyperty-toolkit#6]
I ran into this problem on my Windows (64 bit) system  during the installation process. 
Just info in case someone else runs into the same problem. It doesn't help running the command terminal as administrator. This resolved the problem for me:

* Open the node.js command prompt (Windows button => all programs => node.js => node.js command prompt => run as administrator)

**Comment by pchainho** [comment]
Thx Alice

I suggest to have a kind of "Help" section or md page with these kind of hints

**Comment by acheambe** [comment]
Yes, a Help or Q&A section would make sense to document all the the doubles developers face in using the toolkit.

**Comment by acheambe** [comment]
closing...already added to the troubleshooting section.
