### ISSUE TITLE
Unable to understand how to properly add children to SyncObjectParent / Errors in chat hyperty

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-hyperty-toolkit#9]
As mentioned [here](https://github.com/reTHINK-project/dev-hyperty/issues/20#issuecomment-222174068), I have trouble understanding what is the proper way to add a child/children to a SyncObjectParent.

Based on discussion with @pchainho [here](https://github.com/reTHINK-project/dev-service-framework/issues/41), from what I understand, I am supposed to add a "Children" object _as a child_, which immediately is confusing, since the function `addChild` implies adding a "Child" object to the parent object, which seems to be wrong.

The function `addChild` is defined like this:
```
/**
 * Create and add a children to the subscription group.
 * @param {String} resource - Resource name, one of the items in the schema.properties.scheme of the parent object.
 * @param {JSON} initialData - Initial data of the child
 * @return {Promise<DataObjectChild>} - Return Promise to a new Children.
 */
addChild(resource, initialData) {...}
```
So the function is called `addChild`, but you use the function function to `Create and add a children to the subscription group`, and the object you provide is actually the `Initial data of the child`. __What is it now, Child or Children?__

Then, the first argument `resource` is supposed to be `Resource name, one of the items in the schema.properties.scheme of the parent object.`, but that is not the case with any use of addChild I could find (namely [hyperty-chat](https://github.com/reTHINK-project/dev-hyperty-toolkit/blob/master/src/hyperty-chat/Chat.js#L148) and [GroupChat](https://github.com/reTHINK-project/dev-hyperty/blob/master/src/group-chat/GroupChat.js#L5)). In GroupChat,`addChild` is used like this:
```
this._dataObject.addChild('chatmessages', {chatMessage: message, distance: distance, position: this.position.value})
```
First of all, what data model is the object `{chatMessage: message, distance: distance, position: this.position.value}` supposed to comply to? Based on the [Communication Data Model](https://github.com/reTHINK-project/dev-service-framework/tree/master/docs/datamodel/data-objects/communication), it doesn't comply to either "ChatMessages" or "ChatMessage". So what is it based on, or do Child/Children Objects not need to comply to any schema and can be defined arbitrarily? 

May I add that the scheme field is not defined in the Data Models? So I wouldn't even know what I would have to declare as the resource name in my implementation (that is supposed to comply to the [Context Data Model](https://github.com/reTHINK-project/dev-service-framework/tree/master/docs/datamodel/data-objects/context)).

Secondly, the first argument of addChild in this example is "chatmessages", but shouldn't it be "comm", based on the "schema.properties.scheme of the parent object"? The schema of the parent object (Communication) is defined like this:
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "Communication",
	"type": "object",
        "properties": {
		"scheme": {
			"constant": "comm"
		},
		"children": {
			"constant": ["chatmessages"]
		}
	}
}
```
You can see two things here. First, that the schema does not represent the Communication Data Model in any shape or form. Secondly, as you can see, "schema.properties.scheme of the parent object" should be "comm". This is not the case in the example. Instead, it uses the entry of the "children" array.

So, finally, these are the questions I would like to have answered:

1. Do I add "Child" or "Children" objects with addChild? (Please make function name and description consistent and understandable)
2. What is the first argument (`resource`) in addChild supposed to represent?
3. Do Child/Children objects have to comply to a dataschema? If yes, how to you specify this dataschema, like it is specified when doing `syncher.create()`?

I would be very thankful if either the provided examples would be updated to be in line with the standards defined, or  a code example would be added here, showing how `addChild` is supposed to be used properly.

**Comment by pchainho** [comment]
I still have to process this long post but a quick answer is:
you add "child" to "children" where "children" is a kind of child container. "children" are not programmaticaly created but they are defined with data object schema itself

We will update the json-schema very soon. You can see the source code from the Group Chat where addChild(..) is used.

Later, we should also include in the tutorial the usage of addChild() and perhaps even a hello world.

**Comment by Endebert** [comment]
> You can see the source code from the Group Chat where addChild(..) is used.

As stated in my initial comment, I did have a look at the code of GroupChat and based on that I wasn't able to conclude which class is supposed to be used:
> In GroupChat, `addChild` is used like this: 
```
this._dataObject.addChild('chatmessages', {chatMessage: message, distance: distance, position: this.position.value})
```
First of all, what data model is the object `{chatMessage: message, distance: distance, position: this.position.value}` supposed to comply to? __Based on the Communication Data Model, it doesn't comply to either "ChatMessages" or "ChatMessage".__ So what is it based on, or do Child/Children Objects not need to comply to any schema and can be defined arbitrarily?

From what I can gather from the GroupChat code, as long as I provide a string from the `children` array as the first argument for `addChild()`, I can add whatever object I want without any validation whatsoever.

**Comment by pchainho** [comment]
`chatMessage` is still compliant with Communication.ChatMessage even if it has an extra attribute. Anyway, as I mentioned somewhere else to @dvilchez there should be a schema describing this extended communication object. 

> From what I can gather from the GroupChat code, as long as I provide a string from the children array as the first argument for addChild(), I can add whatever object I want without any validation whatsoever.

No, it has to comply with the schema describing the associated SyncObjectChild.

In the meanwhile I'm trying to improve the documentation of the [syncher API](https://github.com/reTHINK-project/dev-service-framework/blob/develop/docs/specs/service-framework/syncher.md). pls have a look

**Comment by Endebert** [comment]
> `chatMessage `is still compliant with Communication.ChatMessage even if it has an extra attribute. 

Not, it isn't. Let's check the json schema for the ChatMessage class:
```
"ChatMessage": {
	"type": "object",
	"stereotype": "syncobjectchild",
	"required": ["message"],
	"properties": {
		"message": {
			"type": "string"
		}
	}
}
```
As you can clearly see from the schema, the object needs to have a required property `message`, which it doesn't have, **i.e. it is not compliant with the schema**.

**Comment by pchainho** [comment]
> As you can clearly see from the schema, the object needs to have a required property message, which {chatMessage: message, distance: distance, position: this.position.value} doesn't have, i.e. it is not compliant with the schema.

right, I missunderstood the name of the atribute with the name of the value. @dvilchez can you fix this, pls ie rename `ChatMessage.chatMessage` attribute to `ChatMessage.message`

> I just did a quick check to see if addChild is described differently there, but it has the exact same problem...
> ...
> And again it is stated "Create and add a children to the subscription group", clearly saying that the object you try to attach is supposed to be a children object, not a child object.

Thanks for this:  I've just improved/fixes the description according to this feedback. Pls have a look again.

> Is 'chatmessages' "one of the items in the schema.properties.scheme of the parent object"? No, it is not. Both arguments are wrong. And that is the example I'm supposed to learn from.

Not the "scheme" attribute but the "children" attribute. By the way, the example you are looking is from Quobis. We have renamed the GroupChat developed by ALB to GroupChatManager and the most updated version is at:

https://github.com/reTHINK-project/dev-hyperty/tree/only-source/src/group-chat-manager

**Comment by Endebert** [comment]
> By the way, the example you are looking is from Quobis. We have renamed the GroupChat developed by ALB to GroupChatManager and the most updated version is at:
>
>https://github.com/reTHINK-project/dev-hyperty/tree/only-source/src/group-chat-manager

And what is this supposed to tell me? The same problem exists in [group-chat-manager](https://github.com/reTHINK-project/dev-hyperty/blob/only-source/src/group-chat-manager/ChatController.js#L142):
```
dataObject.addChild('chatmessages', {chatMessage: message})
```
And the [hyperty-chat](https://github.com/reTHINK-project/dev-hyperty-toolkit/blob/master/src/hyperty-chat/Chat.js#L148) **that is shipped with the toolkit** also does it wrong

**Comment by pchainho** [comment]
it seems the problem was caused at the very beginning. @vitormsilva will fix this

**Comment by dvilchez** [comment]
To be honest, I implemented it like in the examples but I don't understand it. 
I don't know what this notation stand for
`"children": {
            "constant": ["chatmessages"]
        }`

I was seeking it in the JSON Schema documentation but I didn't  find anything. However, I know because @shumy explain me, Syncher is subscribed to this resource "chatmessages"and that is the reason because you have to send "chatmessages as a resource in addChild.

I am implementing a notification hyperty right now and I am using Communication Schema that is supposed to be generic for any communication but I have to use "chatmessages" as a resource and define ChatMessage even if I am not sending chat messages.

**Comment by vitormsilva** [comment]
Hi,

I fix this problem on [group-chat-manager](https://github.com/reTHINK-project/dev-hyperty/blob/only-source/src/group-chat-manager/ChatController.js#L142).

```
dataObject.addChild('chatmessages', {message: message})
```

@dvilchez you could fix yours.

**Comment by pchainho** [comment]
This was fixed / clarified. reopen if needed
